version: '3'
services:
  redis-server:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - celery-net

  celery-worker:
    build: .
    depends_on:
      - redis-server
    networks:
      - celery-net

networks:
  celery-net:
