version: '3'
services:
  redis-server:
    image: redis:latest
    ports:
      - "6379:6379"
  
  celery-worker:
    container_name: celery_worker
    build: .
    command: celery -A celery_worker.app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis-server
  
  celery-beat:
    container_name: celery_beat 
    build: .
    command: celery -A celery_worker.app beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - celery-worker

  celery_flower:
    container_name: flower
    build: .
    command: celery -A celery_worker.app flower
    ports:
      - "5556:5555"
    depends_on:
      - redis-server
      - celery-worker

